language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  
script:
  # Run unit tests
  - npm test
  
notifications:
  email:
    recipients:      
      - oleg@webmarketingroi.com.au
    on_success: always
    on_failure: always
